################ English language ##################
[en]
label = "En"
locale = "en-us"
contentDir = "content/english"
weight = 1

[cn]
label = "中文"
locale = "zh-cn"
contentDir = "content/cn"
weight = 2
